[project]
name = "wp-mpm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "h5py==3.9.0",
    "torch==2.0.1",
    "warp-lang==0.10.1",
]
